name: Poem of the day
favicon: null
layout_spectrum: 0.27551372605375946
typography_spectrum: 0.717641256051138
title: Poem of the day
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.05483662476763129
  lightness: 0.6891133815515786
  saturation: 0.5272656062152237
  rhythmicContrast: 0.546701394720003
purpose: []
